---
abstract: 'analyze the output of du and find the most space-consuming directories.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::Differences: '0'
  Test::More: '0'
  Test::Trap: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Du-Analyze
requires:
  Getopt::Long: '0'
  List::MoreUtils: '0'
  MooX: '0'
  MooX::late: '0.010'
  Pod::Usage: '0'
  autodie: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-Du-Analyze
  repository: https://github.com/shlomif/perl-App-Du-Analyze.git
version: 0.0.3
